// Generated by `npm run levels` — do not edit by hand.
import type { LevelDef } from '@/game/types';

export const levelIndex = [
  require('@/assets/levels/week01/w01-d1.json'),
  require('@/assets/levels/week01/w01-d2.json'),
  require('@/assets/levels/week01/w01-d3.json'),
  require('@/assets/levels/week01/w01-d4.json'),
  require('@/assets/levels/week01/w01-d5.json'),
  require('@/assets/levels/week02/w02-d1.json'),
  require('@/assets/levels/week02/w02-d2.json'),
  require('@/assets/levels/week02/w02-d3.json'),
  require('@/assets/levels/week02/w02-d4.json'),
  require('@/assets/levels/week02/w02-d5.json'),
] as LevelDef[];
